# Generated by Django 3.1.3 on 2020-11-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebPageOwnerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(help_text='Enter owner of webpage', max_length=20)),
            ],
            options={
                'ordering': ['-owner_name'],
            },
        ),
    ]
