# Generated by Django 3.1.3 on 2020-11-24 17:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20201124_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webpageownerinfo',
            options={'ordering': ['-owner_name', 'owner_twitter', 'owner_description']},
        ),
        migrations.AlterField(
            model_name='webpageownerinfo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
