# Generated by Django 3.1.3 on 2020-12-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddPlTeamsToDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(help_text='Enter team name (Arsenal)', max_length=30)),
                ('team_id', models.IntegerField(help_text='Enter team id (1) ', max_length=40)),
                ('team_short_name', models.CharField(help_text='Enter team name short (ARS)', max_length=3)),
            ],
            options={
                'ordering': ['-team_id', 'team_name', 'team_short_name'],
            },
        ),
    ]
