# Generated by Django 3.1.3 on 2020-12-03 18:21

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addplteamstodb',
            name='date',
            field=models.DateField(default=datetime.date(2020, 12, 3), help_text='Date entered into database'),
        ),
        migrations.AddField(
            model_name='addplteamstodb',
            name='oppTeamDifficultyScore',
            field=django_mysql.models.ListTextField(models.IntegerField(help_text='1-5'), default=1, size=38),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addplteamstodb',
            name='oppTeamHomeAwayList',
            field=django_mysql.models.ListTextField(models.CharField(help_text='H/A', max_length=1), default=1, size=38),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addplteamstodb',
            name='oppTeamNameList',
            field=django_mysql.models.ListTextField(models.CharField(help_text='Enter team name short (ARS)', max_length=3), default=1, size=38),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addplteamstodb',
            name='team_id',
            field=models.IntegerField(help_text='Enter team id (1) '),
        ),
    ]
